#!/usr/bin/env python
"""Write docs/m0_gate.md: effective-date spot checks for the M0 gate.

For each bank, ten decision dates spread over 2010-2027, with the effective
date the code produces (``meetings.effective_date`` on the committed
calendars and maintenance periods), the rule applied, any policy-rate change
recorded on that effective date, and the source URL of the meeting row. The
dates are chosen by hand (rate changes, regime changes, holiday rolls, published
exceptions); everything else is computed. Published implementation dates (ECB
maintenance table, meetings/published_effective.csv) win over the rules. Reads committed CSVs only.

    python scripts/m0_gate.py            # writes docs/m0_gate.md
"""
from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from stircurve.refdata.calendars import Calendar  # noqa: E402
from stircurve.refdata.maintenance import load_maintenance_periods, load_policy_rates, validate_maintenance_periods  # noqa: E402
from stircurve.refdata.meetings import (BANK_CALENDAR, ecb_rule_effective, effective_date, load_meetings,  # noqa: E402
                                        load_published_effective, published_lookup)

D = dt.date.fromisoformat
PICKS = {
    "fed": ["2010-08-10", "2012-09-13", "2015-12-16", "2017-06-14", "2020-03-03",
            "2020-03-15", "2022-03-16", "2024-09-18", "2026-09-16", "2027-12-08"],
    "ecb": ["2010-05-06", "2011-04-07", "2012-07-05", "2014-06-05", "2015-01-22",
            "2019-09-12", "2022-07-21", "2023-12-14", "2024-06-06", "2027-04-29"],
    "boe": ["2010-03-04", "2013-08-01", "2016-08-04", "2017-11-02", "2020-03-11",
            "2020-03-19", "2022-02-03", "2024-08-01", "2026-09-17", "2027-12-16"],
    "boj": ["2010-05-10", "2010-10-05", "2014-10-31", "2016-01-29", "2016-09-21",
            "2020-03-16", "2024-03-19", "2025-12-19", "2026-06-16", "2026-09-18"],
}
BOJ_CONFIRMED = {D("2024-03-19"): D("2024-03-21"), D("2025-12-19"): D("2025-12-22"), D("2026-06-16"): D("2026-06-17")}
ANCHORS = {"fed": ["target_lower", "target_upper"], "ecb": ["dfr", "mro", "mlf"], "boe": ["bank_rate"],
           "boj": ["call_target_midpoint", "policy_rate_balance_rate", "ioer"]}


def _skipped(cal: Calendar, a: dt.date, b: dt.date) -> str:
    days = [a + dt.timedelta(days=i) for i in range(1, (b - a).days)]
    names = [f"{d:%a %d %b} {cal.holidays[d]}" for d in days if d in cal.holidays]
    return f" (skips {', '.join(names)})" if names else ""


def _rule(bank: str, dec: dt.date, eff: dt.date, cal: Calendar, mps_by_meeting: dict, overrides: dict,
          lookup: dict) -> str:
    rule = effective_date(bank, dec, cal)
    if dec in overrides:
        return f"published implementation date ({overrides[dec][1]}); rule would give {rule} ✱"
    if bank in ("fed", "boj") and lookup.get(dec) == eff and eff != rule:
        return f"published implementation date (policy-rate change on {eff}); rule would give {rule} ✱"
    if bank == "fed":
        return f"+1 `us_fed` business day{_skipped(cal, dec, eff)}" + (" (Sunday decision)" if dec.weekday() == 6 else "")
    if bank == "boe":
        return "same day"
    if bank == "boj":
        return f"next `jp` business day{_skipped(cal, dec, eff)}"
    mp = mps_by_meeting.get(dec)
    fallback = ecb_rule_effective(dec, cal)
    note = "" if fallback == eff else f"; Wednesday-after fallback would give {fallback} ✱"
    return f"start of MP {mp.label} ({mp.start}..{mp.end}), published table{note}"


def _changes(rates, anchors, day: dt.date) -> str:
    out = []
    for a in anchors:
        hist = [r for r in rates if r.anchor == a]
        for i, r in enumerate(hist):
            if r.effective_date == day and not (i and hist[i - 1].rate == r.rate):   # tables restate unchanged rates
                prev = f"{hist[i - 1].rate:g} → " if i else ""
                conf = "" if r.confidence == "primary" else f" [{r.confidence}]"
                out.append(f"{a} {prev}{r.rate:g}{conf}")
    return "; ".join(out) or "—"


def main() -> int:
    mps = load_maintenance_periods()
    mps_by_meeting = {m.meeting_decision_date: m for m in mps}
    lines = [
        "# M0 gate: effective-date spot checks",
        "",
        "Generated by `python scripts/m0_gate.py` from the committed reference CSVs after the live",
        "updater runs of 8 Oct 2026. For each bank: ten decision dates across 2010–2027, the effective",
        "date the code produces (`stircurve.refdata.meetings.effective_date` on the committed",
        "calendars and maintenance periods), the rule applied, the policy-rate change recorded on",
        "that effective date (if any), and the source of the meeting row. AC: please check each",
        "effective date against the primary source.",
        "",
        f"ECB maintenance periods: {len(mps)} ({mps[0].label} {mps[0].start} – {mps[-1].label} {mps[-1].end}); "
        f"`validate_maintenance_periods`: {'; '.join(validate_maintenance_periods(mps)) or 'no gaps, overlaps or implausible lengths'}.",
        "",
    ]
    titles = {"fed": "Fed (FOMC)", "ecb": "ECB", "boe": "BoE (MPC)", "boj": "BoJ (MPM)"}
    for bank, picks in PICKS.items():
        cal = Calendar.load(BANK_CALENDAR[bank])
        rates = load_policy_rates(bank)
        rows = {m.decision_date: m for m in load_meetings(bank)}
        lookup, overrides = published_lookup(bank), load_published_effective(bank)
        lines += [f"## {titles[bank]}", "",
                  "| Decision | Effective (code) | Rule applied | Rate change on effective date | Source |",
                  "| --- | --- | --- | --- | --- |"]
        for s in picks:
            dec = D(s)
            m = rows[dec]
            eff = effective_date(bank, dec, cal, lookup)
            assert eff == m.effective_date, (bank, dec, eff, m.effective_date)   # code agrees with the CSV
            kind = "" if m.scheduled else " (unscheduled)"
            conf = " ✔ confirmed (D15)" if BOJ_CONFIRMED.get(dec) == eff else ""
            lines.append(f"| {dec:%a %Y-%m-%d}{kind} | {eff:%a %Y-%m-%d}{conf} | {_rule(bank, dec, eff, cal, mps_by_meeting, overrides, lookup)} "
                         f"| {_changes(rates, ANCHORS[bank], eff)} | {m.source_url} |")
        lines.append("")
        if bank == "ecb":
            lines += ["✱ marks dates where the published table and the rule fallback differ; the table wins (D15).", ""]
        if bank == "fed":
            lines += ["2020-03-03: unscheduled meeting 2–3 Mar (the historical page dates it 2 Mar; the statement was",
                      "released 3 Mar, which is the decision date); implementation 4 Mar per the implementation note,",
                      "recorded in `meetings/published_effective.csv`. ✱ = published date; here it equals the rule.", ""]
        if bank == "boe":
            lines += ["2020-03-11 and 2020-03-19 are special meetings (`boe_unscheduled.csv`, with 2001-09-18). Every",
                      "Bank Rate change since June 1997 falls on a meeting date (tested).", ""]
        if bank == "boj":
            lines += ["The three D15 confirmations (✔) reproduce. 2016-01-29 (✱): the negative rate applied from the",
                      "reserve maintenance period commencing 16 Feb 2016 (statement k160129a); recorded in",
                      "`meetings/published_effective.csv`. 2010-10-05 (✱): the statement says the new guideline",
                      "applied 'effective immediately', as for every change 2006-2010; since 2024 the statements",
                      "date it the next business day. Unscheduled meetings (from the minutes) are in",
                      "`boj_unscheduled.csv`.", ""]
    out = ROOT / "docs" / "m0_gate.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
